all:
	gcc -c ichigojam.c -o out/ichigojam.o
	gcc -c kawakudari.c -o out/kawakudari.o
	gcc -o kawakudari out/ichigojam.o out/kawakudari.o -lm -lallegro -lallegro_primitives

clean:
	rm kawakudari
	rm out/ichigojam.o
	rm out/kawakudari.o
